### ISSUE TITLE
Unexpected Legend Behavior in Treemap

### ISSUE THREAD

**Issue by tgrehn** [d3plus/d3plus-viz#103]
I have a dataset of companies and their products. I created a Treemap and grouped the dataset by company and products. 

If a company has only one product in the dataset, the Legend does not display the company's name but the product's.

I would expect the Legend to show the first level's identifier (here: company name) and not the second level's identifier. 

Example: http://jsfiddle.net/g149pjqo/3/

**Comment by davelandry** [comment]
Good catch @tgrehn, thanks for reporting.

@cnavarreteliz can you look into this? Could be related to this:

https://github.com/d3plus/d3plus-viz/blob/master/src/_drawLegend.js#L9-L12

Or this:

https://github.com/d3plus/d3plus-viz/blob/master/src/Viz.js#L278-L287

**Comment by tgrehn** [comment]
Wow, stunned by your quick replies and fixes! Thank you very much! 

I patched my local files and it works as expected now!

**Comment by tgrehn** [comment]
Could you tell me when the fix will be available?
