### ISSUE TITLE
implement data threshold grouping

### ISSUE THREAD

**Issue by davelandry** [d3plus/d3plus-viz#111]
d3plus 1.0 has a feature that groups data under a certain percentage ("threshold") into an `"Values < X%"` category. This should be implemented in the new d3plus:
- [x] a `threshold` method that accepts a _Number_ or an accessor _Function_
- [x] a `thresholdKey` method that tells d3plus-viz what value to use (accepts a _String_ or a _Function_). It will then be on each visualization (ie. Treemap) to set a default value for this method (ie. when a user defines `sum`, also define `thresholdKey` if it has not been defined.
- [x] grouping logic should be implemented [after this line](https://github.com/d3plus/d3plus-viz/blob/master/src/Viz.js#L322)
- [x] if it is a _Function_, pass the function the `flatData` and expect a returned _Number_
- [x] add a `key` to the `nest` that nests any data that has a `thresholdKey` less than that the overall total for that group and give it a different `key`

**Comment by frabarz** [comment]
I need a clarification on the way the new category would be made. The `"Values < X%"` makes me think on a "all items whose `d[value]` is lower than `sum(d[value]) * threshold`" criteria, but Carlos made me think it would also useful to group "all items belonging to the lower `threshold * 100`% of the data".

**Comment by davelandry** [comment]
from the Slack conversation: let's make it "all items whose `value` is lower than the `overallTotal * threshold`, where `overallTotal` is calculated across the entire dataset (not for each group)

**Comment by davelandry** [comment]
implemented!
