### ISSUE TITLE
method for disable hide/solo behavior in legend

### ISSUE THREAD

**Issue by cnavarreteliz** [d3plus/d3plus-viz#123]
I would like to include a custom method for disable hide/solo options availables in the legend.

**Comment by davelandry** [comment]
@cnavarreteliz unless you feel strongly otherwise, I'd like to not add an extra method to manage this, and instead just require the user to disable the click event and the footer like so:

```js
.legendTooltip({footer: ""})
.on({"click.legend": () => {}})
```
