### ISSUE TITLE
 hierarchy with more that 2 levels shows incorrect data in level 3

### ISSUE THREAD

**Issue by nalhadad** [d3plus/d3plus-viz#135]
If we have a TreeMap/Pie with hierarchy with more that 2 levels, the shown data is not correct in the third level (the father is the second level and not the combination of the first and the second)

### Steps to Reproduce (for bugs)
(http://jsfiddle.net/54Ldjcq8/1/)
click two times on the treemap to reach the level of "month"
the shown data concern all the data for the year '2015' and not the data that is related to (country+year)

**Comment by davelandry** [comment]
@nalhadad thanks for reporting, fixed with the latest release: http://jsfiddle.net/8vLdm9eg/
