### ISSUE TITLE
double space in title causes other spaces after to be removed?

### ISSUE THREAD

**Issue by jspeis** [d3plus/d3plus-viz#14]
Just noticed this, not sure if I messed up a configuration or something bug thought I would file this in case anyone else encountered a similar issue?

http://codepen.io/jspeis/pen/RKrmPM

Notice that there is a double space "  " after the words "DOUBLE SPACE". If I delete the double space in the title then the spacing in the over words ("Latest Available Data") looks right.

**Comment by davelandry** [comment]
Issue moved to [d3plus/d3plus-text #55](https://github.com/d3plus/d3plus-text/issues/55) via [**ZenHub**](https://www.zenhub.com/)
