### ISSUE TITLE
Gracefully handle case where dataFormat fails to return data

### ISSUE THREAD

**Issue by jhmullen** [d3plus/d3plus-viz#160]
### Expected Behavior
If the user fails to return data in dataFormat, the viz should either use the pre-formatted data or `[]`, and provide a warning to the user.

### Current Behavior
If the user forgets to return data in `dataFormat`, it will red-screen crash the page. This is fine for direct usage, but in the CMS, it crashes the entire interface and requires database recovery. React 16 Error Boundaries can't help here because the code happens in an event handler.

### Steps to Reproduce (for bugs)

1. Create A Viz
2. Add a dataFormat key without a return statement
3. Observe explosion

### Extra notes
The code in question in load.js. Interestingly, if the fetch itself got an error, the behavior is to use `[]`:

https://github.com/d3plus/d3plus-viz/blob/master/src/data/load.js#L87

However, after the user-defined formatter is applied, there is no such catch:

https://github.com/d3plus/d3plus-viz/blob/master/src/data/load.js#L100

This means if the user messes up their dataFormat, the whole application crashes - which in the CMS can be quite difficult to recover.

**Comment by davelandry** [comment]
Fixed with d3plus-viz v1.0.9 (@jhmullen I'm not sure which project you were waiting on this for, but update d3plus-viz and you should be good to go)
