### ISSUE TITLE
Use d3plus-viz with Angular (4)

### ISSUE THREAD

**Issue by dpineiden** [d3plus/d3plus-viz#47]
Hello

I'm developint an app and try to use d3plus-viz.
The framwork reconize the classes and fucntions, but when i load the data to show on the browser it only resize the 'div' in what the chart have to be show.

I've tried with that example and nothing:

```js
var graph_viz = new Viz();

var connections = [
  { "source": "alpha", "target": "beta", "strength": 1.25 },
  { "source": "alpha", "target": "gamma", "strength": 2.463 },
  { "source": "beta", "target": "delta", "strength": 0.823 },
  { "source": "beta", "target": "epsilon", "strength": 1.563 },
  { "source": "zeta", "target": "gamma", "strength": 3.125 },
  { "source": "theta", "target": "gamma", "strength": 0.732 },
  { "source": "eta", "target": "gamma", "strength": 2.063 }
];

graph_viz
  .data(connections)
  //.color('green')
  //.select('#csk_graph')
  //.label('CSK Graph')
  .render();
```

**Comment by davelandry** [comment]
The d3plus-viz module doesn't actually draw any visualizations. It is an abstract class that all the other visualizations, like [d3plus-network](https://github.com/d3plus/d3plus-network), use as a shell.

Also, when using d3plus in the browser, all of the modules are added to the `window` in a `d3plus` object. Here's an example that has the correct syntax: https://d3plus.org/examples/d3plus-network/getting-started/

You also need to include a nodes array with x and y positions.
