### ISSUE TITLE
tooltips on mobile bar chart renders partially off screen

### ISSUE THREAD

**Issue by jspeis** [d3plus/d3plus-viz#60]
### Expected Behavior

To have tooltips wrap text to fit within the viewport

### Current Behavior

Tooltip extends text off screen

### Steps to Reproduce (for bugs)

1. https://jsfiddle.net/m3eq59rq/

<img width="594" alt="screen shot 2018-03-23 at 7 48 41 am" src="https://user-images.githubusercontent.com/87581/37827627-a1e67fbc-2e6e-11e8-9372-551a91fc3c6e.png">

<img width="341" alt="screen shot 2018-03-23 at 7 43 04 am" src="https://user-images.githubusercontent.com/87581/37827645-b32aef1a-2e6e-11e8-9eda-c90d52e51111.png">

**Comment by davelandry** [comment]
Moved to https://github.com/d3plus/d3plus-tooltip/issues/26
