### ISSUE TITLE
error when disabling noDataMessage

### ISSUE THREAD

**Issue by davelandry** [d3plus/d3plus-viz#65]
### Expected Behavior
If `noDataMessage` is set to false, there should be no status message on the screen once the data has finished loading.

### Current Behavior
The `loadingMessage` is not being removed.

### Steps to Reproduce (for bugs)

<img width="1258" alt="screen shot 2018-03-30 at 2 19 34 pm" src="https://user-images.githubusercontent.com/1847581/38149344-3b41199c-3428-11e8-892a-a7ad284bb8af.png">

### Your Environment

* Browser Name: Chrome
* Operating System and Version: macOS High Sierra

**Comment by nbond211** [comment]
Can you give me steps to reproduce? I just tried setting `noDataMessage` to `false` and I am not getting this bug.

**Comment by davelandry** [comment]
You need to be a visualization that will draw something regardless of data, like d3plus-network or d3plus-geomap. Here's the code I was using in d3plus-network:

```html
<!doctype html>
<html>

<head>

  <meta charset="utf-8">
  <script src="../build/d3plus-network.full.js"></script>

</head>

<body></body>

<script>

  var nodes = [
    {id: "alpha",   x: 1,   y: 1},
    {id: "beta",    x: 2,   y: 1},
    {id: "gamma",   x: 1,   y: 2},
    {id: "epsilon", x: 3,   y: 2},
    {id: "zeta",    x: 2.5, y: 1.5},
    {id: "theta",   x: 2,   y: 2}
  ];

  var links = [
    {source: 0, target: 1},
    {source: 0, target: 2},
    {source: 3, target: 4},
    {source: 3, target: 5},
    {source: 5, target: 0}
  ];

  links.forEach(link => {
    link.source = nodes[link.source];
    link.target = nodes[link.target];
  });

  new d3plus.Network()
    .links(links)
    .nodes(nodes)
    .label(d => d.id)
    .noDataMessage(false)
    .render();

</script>

</html>
```
