### ISSUE TITLE
brush control icon not correctly loading on certain mobile devices

### ISSUE THREAD

**Issue by jspeis** [d3plus/d3plus-viz#68]
### Expected Behavior

The brushing icon should be appear normally
<img width="68" alt="screen shot 2018-04-04 at 10 06 15 am" src="https://user-images.githubusercontent.com/87581/38312466-d87368e4-37ef-11e8-83b5-db6ce8a6649a.png">

### Current Behavior

For users of Samsung Galaxy on Chrome using Android 7 the icon is not loading correctly
![screenshot_20180404-082833](https://user-images.githubusercontent.com/87581/38312556-0c0ee6ba-37f0-11e8-9037-3170fb240f39.png)

### Steps to Reproduce (for bugs)

1. See screenshot above (have not been able to reproduce in Chrome emulator)

### Your Environment

* Browser Name: Chrome
* Operating System and Version: Android v7.0

**Comment by davelandry** [comment]
This is a very strange one... as that icon SHOULD be a standard HTML entity available in most fonts: http://graphemica.com/%E2%A7%88

We're using the following font-family declaration: 

```css
'Roboto', 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif
```

I'm able to get that rendering in all of the fonts on my machine, @jspeis is there any way on Android you can see what font that is being rendered with?

**Comment by jspeis** [comment]
it actually works fine on my android phone. but using[BrowserStack](https://www.browserstack.com) I was able to open the site using a samsung android device. t looks like it does use Roboto but that character doesn't render:

<img width="1192" alt="screen shot 2018-04-05 at 9 11 23 am" src="https://user-images.githubusercontent.com/87581/38367769-9345bd86-38b1-11e8-9f51-34c56413c924.png">

<img width="230" alt="screen shot 2018-04-05 at 9 11 36 am" src="https://user-images.githubusercontent.com/87581/38367765-901c5aa2-38b1-11e8-849a-2d04cd14dabf.png">

**Comment by davelandry** [comment]
@jspeis do you have a paid account with BrowserStack? Also, what's the priority on getting this issue fixed? I obviously want to figure out an internal default solution that works for all browsers, but that will take some digging/time. In the meantime, I could (and should) hook up a way to override those HTML entities, but I'm just wondering if that can wait until we're actually in the code for one fell swoop.

**Comment by jspeis** [comment]
I don't have a paid account but I used a free account to recreate the issue. In terms of timeline we are aiming to wrap up dev a week from Friday.

**Comment by davelandry** [comment]
Swapped for this character, which I tested in BrowserStack: http://graphemica.com/%C2%A4

It's from one of the older unicode sets, so it should be supported by more fonts families.
