### ISSUE TITLE
create method to disable the ColorScale (but maintain shape coloring)

### ISSUE THREAD

**Issue by davelandry** [d3plus/d3plus-viz#83]
### Expected Behavior
Users should be able to use the color scale logic to fill shapes, but also have the ColorScale be invisible.

### Current Behavior
The `colorScale` method defines both the variable to be used AND the visibility of the scale.

**Comment by frabarz** [comment]
The documentation says for the `colorScalePosition` property:

>Acceptable values are "top", "bottom", "left", "right", and false. A false value will cause the color scale to not be displayed, but will still color shapes based on the scale.

However this is not the current behavior.
