### ISSUE TITLE
improve visualization title behavior 

### ISSUE THREAD

**Issue by jspeis** [d3plus/d3plus-viz#88]
Right now if you hover over a bar on a bar chart the default visualization says "D3plus visualization".

![screen shot 2018-07-31 at 10 00 37 am](https://user-images.githubusercontent.com/87581/43464370-f6746210-94a8-11e8-99dc-b59c357f42a4.png)

Was wondering if we could do 2 things:

1. By default, if no title is specified could that tooltip read "Bar chart visualization" or "Treemap visualization" ?
2. Could we also add an option to allow users to specify override the tooltip label without having to necessarily render an additional visible title?

**Comment by davelandry** [comment]
I personally think that, if possible, we should find a way to hide this random little browser pop-up! It only exists now because we needed to set a `<title>` attribute inside of the `<svg>` for better 508 compliance, but it's kind of a nuisance for non-screen reader users IMO

**Comment by davelandry** [comment]
this has been disabled by default
