### ISSUE TITLE
How to go back from active state?

### ISSUE THREAD

**Issue by aaradi** [d3plus/d3plus-viz#91]
When I call the active function, I need to pass a function that returns a boolean: true for the viz to be active and false for it to be inactive, but how do I return to the original state, which is not active nor inactive?

**Comment by davelandry** [comment]
@aaradi the active function determines the active state for specific shapes inside of the visualization. Your accessor gets passed each data point, and you should return `true` for the data points you'd like to be highlighted. Returning `false` for everything with effectively disable the active state.

**Comment by aaradi** [comment]
I'm using this on a tree-map to allow the user to highlight specific rectangles.
As you wrote, returning true for a data point will highlight it by adding a border around the rectangle. Returning false makes the rectangle grayed out.
But how do I return the rectangle to it's default state, without the border and not grayed out?

**Comment by davelandry** [comment]
Returning `false` should return the rectangle back to it's original state. Can you post a JSfiddle with some sample code showing the behavior you're seeing?

**Comment by aaradi** [comment]
[https://jsfiddle.net/j87nvopw/8/](url)

**Comment by davelandry** [comment]
Ahhh I see the problem. You need to pass `false` as a constant to the function: https://jsfiddle.net/j87nvopw/9/
